# Generated by Django 4.2.23 on 2025-07-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dedup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedupjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
